// Database types - will be auto-generated by Supabase CLI later
// For now, manual definitions matching our schema

export type TaskStatus = 'locked' | 'unlocked' | 'in_progress' | 'completed'
export type TaskSize = 'S' | 'M' | 'L'
export type MemberRole = 'owner' | 'member'

export interface Profile {
  id: string
  email: string
  full_name: string | null
  avatar_url: string | null
  created_at: string
  updated_at: string
}

export interface Project {
  id: string
  name: string
  description: string | null
  owner_id: string
  created_at: string
  updated_at: string
}

export interface ProjectMember {
  id: string
  project_id: string
  user_id: string
  role: MemberRole
  joined_at: string
}

export interface Node {
  id: string
  project_id: string
  title: string
  description: string | null
  owner_id: string | null
  status: TaskStatus
  size: TaskSize
  xp_value: number
  position_x: number
  position_y: number
  branch: string // 'dev' | 'biz' | 'launch' or custom
  completion_notes: string | null
  completed_at: string | null
  completed_by: string | null
  created_at: string
  updated_at: string
  // Joined data
  owner?: Profile | null
}

export interface Dependency {
  id: string
  project_id: string
  from_node_id: string
  to_node_id: string
  created_at: string
}

export interface UserProgress {
  id: string
  user_id: string
  project_id: string
  total_xp: number
  level: number
  tasks_completed: number
  streak_days: number
  last_activity_at: string | null
  created_at: string
  updated_at: string
  // Joined data
  user?: Profile
}

export interface ProjectProgress {
  id: string
  project_id: string
  total_xp: number
  tasks_completed: number
  created_at: string
  updated_at: string
}

export interface Achievement {
  id: string
  code: string
  name: string
  description: string
  icon: string
  xp_reward: number
}

export interface UserAchievement {
  id: string
  user_id: string
  achievement_id: string
  project_id: string
  earned_at: string
  achievement?: Achievement
}

export interface EventLog {
  id: string
  project_id: string
  user_id: string | null
  event_type: string
  payload: Record<string, unknown>
  created_at: string
  user?: Profile
}

// API response types
export interface CompleteNodeResult {
  success: boolean
  xp_gained: number
  total_xp: number
  level: number
  level_up: boolean
  unlocked_nodes: string[]
  achievements_earned: Achievement[]
}
